### ISSUE TITLE
When JRE is not compatible with OS error message is tricky to understand

### ISSUE THREAD

**Issue by jamesneale** [palantir/go-java-launcher#14]
When trying to launch using a Unix JRE on OSX go-java-launcher fails with the following error:

```
panic: exec format error

goroutine 1 [running]:
panic(0x166760, 0xc8200baa50)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/palantir/go-java-launcher/launchlib.execWithChecks(0xc8200cc090, 0x24, 0xc8200e0600, 0x8, 0xc)
	/home/ubuntu/.go_workspace/src/github.com/palantir/go-java-launcher/launchlib/launcher.go:93 +0x27a
github.com/palantir/go-java-launcher/launchlib.Launch(0xc8200b9e48, 0xc8200b9e18)
	/home/ubuntu/.go_workspace/src/github.com/palantir/go-java-launcher/launchlib/launcher.go:83 +0xe38
main.LaunchWithConfig(0x7fff5fbff9b2, 0x1f, 0x7fff5fbff9d2, 0x1c)
	/home/ubuntu/.go_workspace/src/github.com/palantir/go-java-launcher/go-java-launcher/main.go:39 +0x389
main.main()
	/home/ubuntu/.go_workspace/src/github.com/palantir/go-java-launcher/go-java-launcher/main.go:56 +0xf6
```

Very hard to debug. Would be nice to fail with a much easier to understand error.

**Comment by uschi2000** [comment]
Not really sure what to do here; suggestions?

**Comment by jamesneale** [comment]
No bright ideas unfortunately - at the very least I thought this might help if someone hits this error in future.
