### ISSUE TITLE
Obtuse error message if JAVA_HOME is set incorrectly.

### ISSUE THREAD

**Issue by jamesneale** [palantir/go-java-launcher#3]
If your JAVA_HOME env var is set to an incorrect location you get the following error message in your logs which is reasonably tricky to debug:

```
panic: no such file or directory

goroutine 1 [running]:
panic(0x1665a0, 0x8202abfc0)
    /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/palantir/go-java-launcher/launchlib.Launch(0x820341e48, 0x820341e18)
    /home/ubuntu/.go_workspace/src/github.com/palantir/go-java-launcher/launchlib/launcher.go:86 +0xf3f
main.LaunchWithConfig(0x7fff5fbffa1a, 0x1f, 0x7fff5fbffa3a, 0x1c)
    /home/ubuntu/.go_workspace/src/github.com/palantir/go-java-launcher/go-java-launcher/main.go:39 +0x389
main.main()
    /home/ubuntu/.go_workspace/src/github.com/palantir/go-java-launcher/go-java-launcher/main.go:56 +0xf6
```

**Comment by uschi2000** [comment]
Fair. Want to make a PR?

**Comment by jamesneale** [comment]
Happy to - might be a couple of days before I get a spare moment though.

**Comment by uschi2000** [comment]
Cool, thanks James.

**Comment by jamesneale** [comment]
#4
